[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[BASE]
source = "container"
container = "library/python"
include_regex = "\\d+\\.\\d+\\.?\\d?-alpine\\d\\.\\d+"

[CERTBOT]
source = "github"
github = "certbot/certbot"
use_max_tag = true
prefix = "v"
